### ISSUE TITLE
Matches details not showing on first click

### ISSUE THREAD

**Issue by efonsecab** [pticostaricags/FairPlayCombined#43]
In the "My Matches" page, there is a button with the text "View Details", the button shows a modal window with more information about the selected user, however, it is not showing on the first click, only after a second click the modal starts to show.

Page code:
https://github.com/pticostaricags/FairPlayCombined/blob/development/src/FairPlayCombinedSln/FairPlayDating/Components/Pages/MyMatches.razor

**Comment by sDEV-eloper** [comment]
By adding StateHasChanged() right after setting showDetailsDialog to true in Line No. 156 (given below), we ensure that the modal dialog is displayed without waiting for the next render cycle.

private void OnViewDetailsClicked(UserProfileModel userProfileModel)
    {
        this.selectedUserProfileModel = userProfileModel;
        this.showDetailsDialog = true;
        StateHasChanged() //added
    }

**Comment by efonsecab** [comment]
> By adding StateHasChanged() right after setting showDetailsDialog to true in Line No. 156 (given below), we ensure that the modal dialog is displayed without waiting for the next render cycle.
> 
> private void OnViewDetailsClicked(UserProfileModel userProfileModel) { this.selectedUserProfileModel = userProfileModel; this.showDetailsDialog = true; StateHasChanged() //added }

Hello @sDEV-eloper , thanks for the recommendations, unfortunately, for this specific situation it does not work. Not even disabling pre-rending has solved the issue.
